### PR TITLE
Add isNullLiteral and isBooleanLiteral utility functions

### PR DESCRIPTION
**Pull request by noamyogev84**
implements #96 

 - add isNullLiteral
 - add isBooleanLiteral

### CODE REVIEW

**Comment by noamyogev84** [comment]
Hi @ajafff !
I hope I added these 2 functions in the right place.

**Comment by ajafff** [comment]
Since these SyntaxKinds are available in TypeScript since forever, the functions can go into `typeguard/2.8/node.ts`. The 3.2 folder is only meant for nodes that were added in typescript@3.2

**Comment by noamyogev84** [comment]
Yup. misunderstood it.
Fixed it now. 👍

**Comment by ajafff** [comment]
published as v3.9.0

**Pull request merged**
